name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "87d6cfc54ea44a97a9eee3c304de7b58" },
  { binding = "SHARE", id = "99386a7903e342818b9d1700476fa42e" }
]